DROP EVENT IF EXISTS evt;

CREATE EVENT evt
ON SCHEDULE EVERY 1 HOUR
DO
BEGIN
UPDATE UserList SET active=0 WHERE end_date<CURRENT_TIMESTAMP;
UPDATE UserRoles SET active=0 WHERE end_date<CURRENT_TIMESTAMP;
END

     
